# # https://bencher.orijtech.com/configuration/
suppress_failure_on_regression: true
# global:
#   reg_min: 10.0
#   imp_min: -10.0
dependencies:
  services:
    dind:
      image: "docker:dind"
      ports: [2375]
environment:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: "overlay2"
