# # https://bencher.orijtech.com/configuration/
suppress_failure_on_regression: true
dependencies:
  services:
    dind:
      image: "docker:dind"
      ports: [2375]
      privileged: true
      network_mode: "host"
environment:
  DOCKER_HOST: "tcp://localhost:2375"
  DOCKER_DRIVER: "overlay2"
